### ISSUE TITLE
try fixing .onion transparent proxying

### ISSUE THREAD

**Issue by grugq** [grugq/PORTALofPi#16]
VirtualAddrNetwork 10.192.0.0/10             
    AutomapHostsOnResolve 1                                              
    TransPort 9040                                                          
    TransListenAddress 172.16.0.1

replace with:

    VirtualAddrNetworkIPv4 172.17.0.0/16

**Comment by ad90df8e708e8fa8153e56a059** [comment]
I am able to resolve .onions without any changes to the current code. Was this an old upstream bug with tor? Unless you are talking about transparently resolving .onions for the Pi's own, non-forwarded traffic, then I think you can mark this resolved.

**Comment by grugq** [comment]
to be honest, I am not sure what the issue was that this describes.

Since there seems to be no problem with actually access `.onion` domains, I'm just going to close this ticket.
