### ISSUE TITLE
ArchARM Setup

### ISSUE THREAD

**Issue by lukemlsna** [grugq/PORTALofPi#21]
Arch no longer offers img files for sd cards to setup the OS, they advise using fdisk to make a boot & root partition the dding the contents of the latest build fetched from them as a tarball. 

I can add a script to do this and update the readme if you think that would be helpful.

**Comment by grugq** [comment]
I see, that is quite annoying.

If you would like to submit a script and update the readme I'll review it. Please issue a pull request for me to evaluate.
